version: '3.9'
services:
  orderbox:
    image: app/menu
    container_name: menu
    build: 
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    volumes:
      - .:/app